### ISSUE TITLE
VIP/VIP+ ranks dont appear

### ISSUE THREAD

**Issue by dragonsky53** [EliteFarmers/Website#195]

**Comment by ptlthg** [comment]
Not sure how I didn't notice this before, but yeah, these don't show up.

To fix this, the rank parsing should be extracted into a new method because there are a lot of conditions that need to be checked instead of the following code being in `playerinfo.svelte`:

```ts
$: rankName =
		player?.rank ??
		(player?.monthlyPackageRank !== 'NONE' ? player?.monthlyPackageRank : player?.newPackageRank) ??
		undefined;
$: rank = getRankDefaults(rankName as RankName);
```
