### ISSUE TITLE
Typo in the donate link for lumini

### ISSUE THREAD

**Issue by NeoNyaa** [EliteFarmers/Website#273]
https://github.com/EliteFarmers/Website/blob/32d2b886c202efe2528bb613dd630206cbfda90d/src/content/credits.ts#L39

The link above points to `https://ko-fi.com/shopelumini` instead of `https://ko-fi.com/shoppelumini`

The current link only contains one instance of the letter `p` whereas the correct link has 2 instances of the letter `p`

**Comment by ptlthg** [comment]
Closed by #274
